// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['handlers']['FileHandler']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['handlers']['FileHandler']['SelectFile']();
}

export function SetContext(arg1) {
  return window['go']['handlers']['FileHandler']['SetContext'](arg1);
}
