// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<types.SelectFileResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
