// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function Crawling(arg1:types.CrawlingRequest):Promise<types.CrawlingResponse>;

export function Cropping(arg1:types.CroppingRequest):Promise<types.CroppingResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shuffling(arg1:types.ShufflingRequest):Promise<types.ShufflingResponse>;
