// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Crawling(arg1) {
  return window['go']['handlers']['ImageHandler']['Crawling'](arg1);
}

export function Cropping(arg1) {
  return window['go']['handlers']['ImageHandler']['Cropping'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handlers']['ImageHandler']['SetContext'](arg1);
}

export function Shuffling(arg1) {
  return window['go']['handlers']['ImageHandler']['Shuffling'](arg1);
}
