// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function Crawling(arg1:types.CrawlingRequest):Promise<types.CrawlingResponse>;

export function Cropping():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shuffling():Promise<void>;
