// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function GetPreferenceInfo():Promise<types.GetPreferenceInfoResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
