// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPreferenceInfo() {
  return window['go']['handlers']['User']['GetPreferenceInfo']();
}
